name: Build & Publish (deploy branch)
on:
  push:
    branches: [ main ]  # troque se sua branch principal for outra

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      # Publica o conteúdo de dist/ numa branch chamada "deploy"
      - name: Publish dist to deploy branch
        env:
          REPO: ${{ github.repository }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          rm -rf out && mkdir out
          cp -r dist/* out/
          cd out
          git init
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "deploy $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          git branch -M deploy
          git remote add origin https://x-access-token:${TOKEN}@github.com/${REPO}.git
          git push -f origin deploy
